#!/bin/bash

### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to run when first starting
# Description:       Something needs to be done when  is
#                    starting at first time.
#                    regenerate ssh host key
### END INIT INFO

N=/etc/init.d/firstrun
MEMTOTAL=$(awk 'BEGIN { printf "%.0f\n", '$(grep MemTotal /proc/meminfo | awk '{print $2}')'/1024/1024 }')

set -e

do_expand_rootfs(){
	device="/dev/mmcblk0"
	((echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device)>/dev/null
	return 0
}

case "$1" in
	start)
		reboot=false
		echo ""
		toilet -f standard "first run"
		
		# if we have 1G ram reduce RAMLOG size 
		if (($MEMTOTAL <= 1)); then
			if [ -f "/etc/default/ramlog" ]; then
				sed -e 's/TMPFS_RAMFS_SIZE=512m/TMPFS_RAMFS_SIZE=256m/g' -i /etc/default/ramlog
			fi
		fi
		
		echo "Installing Labjack Exodriver..."
		cd /root/exodriver-master
		/bin/bash ./install.sh
		cd /
		rm -r /root/exodriver-master
		
		echo "Installing Labjack python library..."
		cd /root/LabJackPython-master
		python setup.py install
		cd /
		rm -r /root/LabJackPython-master
		
		echo "Installing pyA20..."
		cd /root/pyA20-0.2.0/
		python setup.py install
		cd /
		rm -r /root/pyA20-0.2.0
		
		echo "Generating SSL cert..."
		echo -e "DE\nNRW\nWuelfrath\nTMES UG\nIT\ninfo@tmes.de\n" | openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/nginx.ssl.key -out /etc/nginx/nginx.ssl.crt -days 3650 -nodes
		
		echo "Generating cookie secret..."
		SLIM_SECRET=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32};echo;)
		sed -e "/secret/c\                'secret' => '$SLIM_SECRET'," -i /usr/share/nginx/www/index.php
		
		echo "Generating SSH key..."
		echo "This process takes around one minute to finish..."
		rm -f /etc/ssh/ssh_host*
		dpkg-reconfigure openssh-server 
		set +e
		
		#expanding rootfs
		echo "Expanding rootfs..."
		if do_expand_rootfs; then
			echo "Expanding rootfs success, rebooting automatically." 
			/sbin/insserv resize2fs
			reboot=true
		else
			echo "Expanding rootfs has failed, see log files." 
		fi
		
		/sbin/insserv -r firstrun
		if $reboot; then
			/sbin/reboot
		fi
		;;
	*)
		echo "Usage: $N {start}" >&2
		exit 1
		;;
esac

exit 0
