#!/bin/bash

### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $all
# Required-Stop:
# Should-Start:      armhwinfo
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to run when first starting
# Description:       Something needs to be done when  is
#                    starting at first time.
#                    regenerate ssh host key
### END INIT INFO

N=/etc/init.d/firstrun

# get some info about the board
MEMTOTAL=$(awk 'BEGIN { printf "%.0f\n", '$(grep MemTotal /proc/meminfo | awk '{print $2}')'/1024/1024 }')

set -e

do_expand_rootfs(){
	device="/dev/mmcblk0"
	((echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device)>/dev/null
	return 0
}

case "$1" in
	start)
		reboot=false
		echo ""
		toilet -f standard "first run"

		# if we have 1G ram reduce RAMLOG size 
		service ramlog enable
		if (($MEMTOTAL <= 1)); then
			if [ -f "/etc/default/ramlog" ]; then
				echo -e "[\e[0;32m ok \x1B[0m] Reducing Ramlog size to 256m"
				sed -e 's/TMPFS_RAMFS_SIZE=512m/TMPFS_RAMFS_SIZE=256m/g' -i /etc/default/ramlog
			fi
		fi

		echo -e "[\e[0;32m ok \x1B[0m] SSH keys recreation. One moment please"
		rm -f /etc/ssh/ssh_host*
		dpkg-reconfigure openssh-server 

		set +e

		#expanding rootfs
		echo "Expanding rootfs..."
		if do_expand_rootfs; then
			echo "Expanding rootfs success, rebooting automatically." 
			/sbin/insserv resize2fs
			reboot=true
		else
			echo "Expanding rootfs has failed, see log files." 
		fi

		/sbin/insserv -r firstrun
		if $reboot; then
			/sbin/reboot
		fi
		;;
	*)
		echo "Usage: $N {start}" >&2
		exit 1
		;;
esac

exit 0
