#! /bin/sh

### BEGIN INIT INFO
# Provides:          resize2fs
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

set -e

N=/etc/init.d/resize2fs

case "$1" in
	start)
		echo timer > /sys/class/leds/green\:ph02\:led1/trigger
		echo 500 > /sys/class/leds/green\:ph02\:led1/delay_on
		echo 500 > /sys/class/leds/green\:ph02\:led1/delay_off

		echo "Resizing SD card file-system..." 
		/sbin/resize2fs /dev/mmcblk0p1 2>/dev/null
		/sbin/insserv -r resize2fs

		echo none > /sys/class/leds/green\:ph02\:led1/trigger
		echo 255 > /sys/class/leds/green\:ph02\:led1/brightness
		;;
	stop)
		echo "Resizing in next start"
		;;
	*)
		echo "Usage: $N {start}" >&2
		exit 1
		;;
esac

exit 0
